Args = -H:Name=ilivalidator \
       -H:Class=org.interlis2.validator.Main \
       -H:EnableURLProtocols=http,https \
       -H:IncludeResourceBundles=org.interlis2.validator.Version \
       -H:IncludeResourceBundles=ch.interlis.ili2c.metamodel.ErrorMessages \
       -H:IncludeResourceBundles=ch.interlis.ili2c.Version \
       -H:IncludeResourceBundles=ch/interlis/iox_j/Version \
       -H:IncludeResourceBundles=ch.ehi.basics.view.resources.GenericFileFilter \
       -H:IncludeResourceBundles=ch.interlis.iox_j.validator.ValidatorMessages \
       -H:IncludeResourceBundles=ch.interlis.ili2c.generator.Interlis1Generator \
       -H:ReflectionConfigurationResources=${.}/reflection-config.json
